matrix:
  include:
    - language: node_js
      node_js:
          - '8'
      env:
          - TEST_DIR=web-app
      before_script:
          - 'export CHROME_BIN=chromium-browser'
          - 'export DISPLAY=:99.0'
          - 'sh -e /etc/init.d/xvfb start'
          - 'npm install -g bower karma karma-cli grunt-cli jshint'
          - 'cd $TEST_DIR'
      script:
          - 'npm install && bower install && gulp travis && npm test'
      branches:
        only:
          - develop
          - feature/travis-ci

    - language: java
      jdk:
        - oraclejdk8
      env:
          - TEST_DIR=mev-api
          - GRADLE_VERSION=3.3
      before_script:
          - 'curl -sLO https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip'
          - 'unzip gradle-${GRADLE_VERSION}-all.zip'
          - 'ln -s gradle-${GRADLE_VERSION} gradle'
          - 'rm gradle-${GRADLE_VERSION}-all.zip'
          - 'cd $TEST_DIR'
      script:
          - 'gradle test'
      branches:
        only:
          - develop
