language: node_js
node_js:
    - '8'
env: 
    - TEST_DIR=web-app

before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install -g bower karma karma-cli grunt-cli jshint'
    - 'cd $TEST_DIR'

script:
    - 'npm install && bower install && gulp travis && npm test'

branches:
  only:
    - develop
    - feature/travis-ci
