language: node_js

node_js:
    - '6'

env: 
    - TEST_DIR=web-app

before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install -g bower karma karma-cli grunt-cli jshint'
    - 'npm install'

script:
    - 'cd $TEST_DIR && npm install && npm test'

branches:
  only:
    - develop
  