version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the third service
    build: web-app # specify image to build container from
    ports:
      - "80:80" # specify port forewarding
    stdin_open: true
    tty: true
    depends_on:
      - express

  express: #name of the second service
    build: node-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    stdin_open: true
    tty: true
    depends_on:
      - spring

  spring: # name of the first service
    build: mev-api # specify the directory of the Dockerfile
    ports:
      - "8080:8080" # specify port forewarding
    stdin_open: true
    tty: true
    depends_on:
      - database

  database: # name of the third service
    image: weshigbee/docker-mongo-sample-datasets # specify image to build container from
    environment:
      - "MONGO_SERVER=mongo"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27027:27017" # specify port forewarding
    stdin_open: true
    tty: true
