version: '2'

services:
  angular: 
    build: web-app 
    ports:
      - "80:80" 
    stdin_open: true
    tty: true
    depends_on:
      - express

  express: 
    build: node-server 
    ports:
      - "3000:3000" 
    stdin_open: true
    tty: true
    depends_on:
      - spring

  spring: 
    build: mev-api 
    ports:
      - "8080:8080" 
    stdin_open: true
    tty: true
    depends_on:
      - database

  database:
    image: weshigbee/docker-mongo-sample-datasets 
    environment:
      - "MONGO_SERVER=mongo"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27027:27017" 
    stdin_open: true
    tty: true
